baseURL = 'https://lewis1766.github.io/' 
languageCode = 'zh'               # 改为 zh 会触发 PaperMod 内置的中文化
title = 'Lewis 的博客'
theme = "PaperMod"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    env = "development"
    author = "Lewis"
    description = "欢迎来到我的个人博客"
    keywords = ["Blog", "Hugo", "PaperMod"]
	mainSections = ["posts"] 
	disableFingerprinting = true
    
    # 功能开关
    ShowReadingTime = true      # 显示阅读时间
    ShowBreadCrumbs = false      # 开启面包屑（返回路径）
    ShowCodeCopyButtons = true  # 显示代码块复制按钮
    ShowShareButtons = false     # 显示分享按钮
    ShowPostNavLinks = true     # 开启文章底部的“上一篇/下一篇”导航

    # --- 主页配置：个人名片模式 ---
    [params.profileMode]
        enabled = true
        title = "你好, 我是 Lewis 👋"
        subtitle = "一名来自HDU的大一信安学生，Vidar-Team成员。下方是我的Github和Instagram"
	imageUrl = "/images/me.jpg"
        displayFullLangName = true

    # --- 社交图标配置 ---
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Lewis1766"

    [[params.socialIcons]]
        name = "instagram"
        url = "https://instagram.com/lewis.5691"


# --- 导航栏菜单配置 ---
[[menu.main]]
    identifier = "home"
    name = "主页"
    url = "/"       # 指向根目录
    weight = 5      # 权重设为最小，让它排在第一个

[[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20

[[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 30

[[menu.main]]
    identifier = "about"      # 新增：关于
    name = "关于"
    url = "/about/"           # 指向刚才创建的 about.md
    weight = 40               # 放在文章后面